### ISSUE TITLE
Add FLOSS-Weekly video to website

### ISSUE THREAD

**Issue by TylerBird** [emissions-api/emissions-api.github.com#15]
To get more informations about the Emissions-API project, we should add the FLOSS-Weekly video to the website. 

- As weblink to youTube or
- as video watchable direktly on the project website

**Comment by tibroc** [comment]
I'm in favor of linking it on our page.

**Comment by EmbeddedHenni** [comment]
because the video is very cool i would link to it. if we get more of this we schould think about a seperate section for this

**Comment by TylerBird** [comment]
Ok. so I will add the link to the website.
