### ISSUE TITLE
Add BMBF Logo to website

### ISSUE THREAD

**Issue by tibroc** [emissions-api/emissions-api.github.com#4]
We have permission from the BMBF to use their logo on our website. We are at the same time required to do so.

**Comment by lkiesow** [comment]
Are we supposed to use [this logo](https://en.wikipedia.org/wiki/German_Aerospace_Center#/media/File:DLR_Logo.svg)? Can we invert the color?

**Comment by TylerBird** [comment]
@tibroc did we get any mail from the DLR where the logo and further informations are given?
I think we should bring their logo to our website soon.

**Comment by lkiesow** [comment]
More logos:
- https://okfn.de/files/projects/PrototypeFund_Header.png
- https://prototypefund.de/wp-content/uploads/2016/07/logo-okfn.svg
- https://prototypefund.de/wp-content/uploads/2016/07/logo-bmbf.svg

**Comment by tibroc** [comment]
We have official permission to use the logo from the BMBF (not the DLR, that's why I edited the issue title) and not in inverted colors. Other logos need to be verified with okfn and pf (I contacted them already).

**Comment by tibroc** [comment]
We also have info from the Prototypefund that we have to use their logo and that of the OKFN on all official publications.
